
from PyQt5 import QtCore, QtGui, QtWidgets


class Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle("Analyzing Differential Equation")
        MainWindow.resize(858, 626)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(100, 65))
        self.widget.setObjectName("widget")
        self.diff_equation = QtWidgets.QTextEdit(self.widget)
        self.diff_equation.setGeometry(QtCore.QRect(550, 20, 231, 31))
        self.diff_equation.setMidLineWidth(1)
        self.diff_equation.setOverwriteMode(False)
        self.diff_equation.setTabStopWidth(80)
        self.diff_equation.setObjectName("diff_equation")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(480, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.exact_equation = QtWidgets.QTextEdit(self.widget)
        self.exact_equation.setGeometry(QtCore.QRect(100, 20, 231, 31))
        self.exact_equation.setMidLineWidth(1)
        self.exact_equation.setOverwriteMode(False)
        self.exact_equation.setTabStopWidth(80)
        self.exact_equation.setObjectName("exact_equation")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 60, 831, 531))
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.layoutWidget = QtWidgets.QWidget(self.tab1)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 831, 511))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.values_page1 = QtWidgets.QWidget(self.layoutWidget)
        self.values_page1.setEnabled(True)
        self.values_page1.setMinimumSize(QtCore.QSize(150, 200))
        self.values_page1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.values_page1.setObjectName("values_page1")
        self.label_3 = QtWidgets.QLabel(self.values_page1)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.values_page1)
        self.textEdit.setGeometry(QtCore.QRect(40, 10, 91, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(self.values_page1)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.values_page1)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 40, 91, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_5 = QtWidgets.QLabel(self.values_page1)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textEdit_3 = QtWidgets.QTextEdit(self.values_page1)
        self.textEdit_3.setGeometry(QtCore.QRect(40, 70, 91, 21))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_6 = QtWidgets.QLabel(self.values_page1)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textEdit_4 = QtWidgets.QTextEdit(self.values_page1)
        self.textEdit_4.setGeometry(QtCore.QRect(40, 100, 91, 21))
        self.textEdit_4.setObjectName("textEdit_4")
        self.checkBox = QtWidgets.QCheckBox(self.values_page1)
        self.checkBox.setGeometry(QtCore.QRect(20, 140, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.values_page1)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.values_page1)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 200, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.button_page1 = QtWidgets.QPushButton(self.values_page1)
        self.button_page1.setGeometry(QtCore.QRect(20, 410, 120, 35))
        self.button_page1.setObjectName("button_page1")
        self.horizontalLayout_2.addWidget(self.values_page1)
        self.graph_page1 = QtWidgets.QWidget(self.layoutWidget)
        self.graph_page1.setEnabled(True)
        self.graph_page1.setMinimumSize(QtCore.QSize(500, 299))
        self.graph_page1.setMaximumSize(QtCore.QSize(400, 16777215))
        self.graph_page1.setObjectName("graph_page1")
        self.horizontalLayout_2.addWidget(self.graph_page1)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab2)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 831, 511))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.values_page2 = QtWidgets.QWidget(self.layoutWidget1)
        self.values_page2.setEnabled(True)
        self.values_page2.setMinimumSize(QtCore.QSize(150, 200))
        self.values_page2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.values_page2.setObjectName("values_page2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.values_page2)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.values_page2)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.values_page2)
        self.checkBox_6.setGeometry(QtCore.QRect(20, 70, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.button_page2 = QtWidgets.QPushButton(self.values_page2)
        self.button_page2.setGeometry(QtCore.QRect(20, 410, 120, 35))
        self.button_page2.setObjectName("button_page2")
        self.horizontalLayout_3.addWidget(self.values_page2)
        self.graph_page2 = QtWidgets.QWidget(self.layoutWidget1)
        self.graph_page2.setEnabled(True)
        self.graph_page2.setMinimumSize(QtCore.QSize(500, 299))
        self.graph_page2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.graph_page2.setObjectName("graph_page2")
        self.horizontalLayout_3.addWidget(self.graph_page2)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 831, 511))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.values_page3 = QtWidgets.QWidget(self.layoutWidget_2)
        self.values_page3.setEnabled(True)
        self.values_page3.setMinimumSize(QtCore.QSize(150, 200))
        self.values_page3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.values_page3.setObjectName("values_page3")
        self.label_11 = QtWidgets.QLabel(self.values_page3)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.textEdit_9 = QtWidgets.QTextEdit(self.values_page3)
        self.textEdit_9.setGeometry(QtCore.QRect(40, 10, 91, 21))
        self.textEdit_9.setObjectName("textEdit_9")
        self.label_12 = QtWidgets.QLabel(self.values_page3)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.textEdit_10 = QtWidgets.QTextEdit(self.values_page3)
        self.textEdit_10.setGeometry(QtCore.QRect(40, 40, 91, 21))
        self.textEdit_10.setObjectName("textEdit_10")
        self.checkBox_10 = QtWidgets.QCheckBox(self.values_page3)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.values_page3)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.values_page3)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 160, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.button_page3 = QtWidgets.QPushButton(self.values_page3)
        self.button_page3.setGeometry(QtCore.QRect(20, 410, 120, 35))
        self.button_page3.setObjectName("button_page3")
        self.horizontalLayout_4.addWidget(self.values_page3)
        self.graph_page3 = QtWidgets.QWidget(self.layoutWidget_2)
        self.graph_page3.setEnabled(True)
        self.graph_page3.setMinimumSize(QtCore.QSize(500, 299))
        self.graph_page3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.graph_page3.setObjectName("graph_page3")
        self.horizontalLayout_4.addWidget(self.graph_page3)
        self.tabWidget.addTab(self.tab3, "")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.diff_equation.setText("y/x+x*cos(x)")
        self.exact_equation.setText("x*sin(x)+c*x")
        self.textEdit.setText("pi")
        self.textEdit_2.setText("1")
        self.textEdit_3.setText("4*pi")
        self.textEdit_4.setText("5")
        self.textEdit_9.setText("5")
        self.textEdit_10.setText("10")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", " y\' = "))
        self.label_2.setText(_translate("MainWindow", " y = "))
        self.label_3.setText(_translate("MainWindow", "X0 = "))
        self.label_4.setText(_translate("MainWindow", "Y0 = "))
        self.label_5.setText(_translate("MainWindow", "  b = "))
        self.label_6.setText(_translate("MainWindow", "  n = "))
        self.checkBox.setText(_translate("MainWindow", "Er"))
        self.checkBox_2.setText(_translate("MainWindow", "ImEr"))
        self.checkBox_3.setText(_translate("MainWindow", "RK"))
        self.button_page1.setText(_translate("MainWindow", "Plot the graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Solution"))
        self.checkBox_4.setText(_translate("MainWindow", "Er"))
        self.checkBox_5.setText(_translate("MainWindow", "ImEr"))
        self.checkBox_6.setText(_translate("MainWindow", "RK"))
        self.button_page2.setText(_translate("MainWindow", "Plot the graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "LTE"))
        self.label_11.setText(_translate("MainWindow", "n0 = "))
        self.label_12.setText(_translate("MainWindow", "N = "))
        self.checkBox_10.setText(_translate("MainWindow", "Er"))
        self.checkBox_11.setText(_translate("MainWindow", "ImEr"))
        self.checkBox_12.setText(_translate("MainWindow", "RK"))
        self.button_page3.setText(_translate("MainWindow", "Plot the graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "GTE"))
